version: '2'
services:
  couchdb:
    image: 'couchdb:1.6'
    container_name: development_couchdb
    ports:
      - '5984:5984'
    networks:
      - development
  redis:
    image: 'redis:3.2'
    container_name: development_redis
    ports:
      - '6379:6379'
    networks:
      - development
networks:
  development: null
