sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
  - "5"
  - "4"
install:
  - npm install
before_script:
  - npm prune
script:
  - make test-coveralls
