sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "8"
  - "10"
services:
  - couchdb
  - redis-server
install:
  - npm install
before_script:
  - npm prune
script:
  - make test-coveralls
